version: "3"
services:
   c9:
     image: c9docker/ide
     container_name: cloud9
     ports:
       - "18001:8181"
     dns:
       - 1.1.1.1
     restart: always
     volumes:
       - ./workspace:/workspace
     command: --auth c9:c9
